### ISSUE TITLE
Understanding of the individual methods!

### ISSUE THREAD

**Issue by DerCap** [eyriewow/merge-models#1]
Hey,
i'm new here so I don't know where to write this yet either.

My request,
can an explanation be added to each method? Where the difference between the three interpolation methods are.

I am a non-expert and would like to know more about this.

And sorry if it is the wrong place for this request.

Regards

**Comment by eyriewow** [comment]
Hi,
As of right now, this project only supports one merging method (linear interpolation).

But Automatic1111's SD Webui has recently added a merging feature that offers three different methods. So, I think you might be confusing projects. The merge method in my project is, as far as I can tell, the same as "Weighted Sum" in Automatic's Webui.

I'm actually not quite sure about how the other two methods in Automatic's Webui work, and I can't find proper documentation of the feature in his wiki. But I'll look into those methods and will probably add them here soon.
