### ISSUE TITLE
Error when merging models

### ISSUE THREAD

**Issue by ArtificialOtaku** [eyriewow/merge-models#5]
I've been getting the following error when trying to merge two models, I was hoping you'd know what the issue is (and thanks in advance for any guidance). 
![Untitled](https://user-images.githubusercontent.com/116858296/199844229-c8a57e98-7033-47a0-8b66-825eea7c33be.jpg)

**Comment by eyriewow** [comment]
Thanks for reporting.

Seems to be related to specifically the NAI model. 
I assume it has a slightly different data structure than most SD models. 

I'll hopefully be able to push a fix out for this soon (tm).

**Comment by ArtificialOtaku** [comment]
You're absolutely right! I tried with a different model, and the merge was perfect, so i guess it's that specific model of NAI that has issues, so thanks for looking into it.

**Comment by jtoy** [comment]
can you show some pictures of results to see how it does?

**Comment by ArtificialOtaku** [comment]
> can you show some pictures of results to see how it does?

Actually, I am now using the WebUI to merge models, seems to be a much straight forward process.
